CREATE TABLE users
(
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL
);

CREATE TABLE news
(
    news_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL
);
